### ISSUE TITLE
Players are messed up

### ISSUE THREAD

**Issue by orthizar** [navhaxs/minecraft-server-dashboard#13]
![MinecraftServerDashboard_E1bOS7guUG](https://user-images.githubusercontent.com/40068335/79049345-5467a680-7c23-11ea-85b2-06a2e12c46ea.png)
On spigot 1.15.2

**Comment by navhaxs** [comment]
Hey @SilvanKohler ! Thanks for the report.

I can see that the string parsing of the player list failed in this code: 
MinecraftServerDashboard/Modules/ProcessPlayerList.vb 

I can't make any promises to get this fixed soon though, as I no longer have the capacity to maintain this old project of mine :( I wrote some of this code 7 years ago! A few years ago I wanted to port this to C# for better maintainability and code practices, but realised that I don't have the time as I once did 🙃
