### ISSUE TITLE
[WIN10] Dashboard will crash at first startup

### ISSUE THREAD

**Issue by ErikSteiner** [navhaxs/minecraft-server-dashboard#5]
I downloaded the program on Windows 10. By executing the exe, the program will crash immediately.
I added the crash-log, but I have no idea of the issue. Maybe it is related to this post here? [LINK](https://social.msdn.microsoft.com/Forums/vstudio/en-US/9e01eb89-5981-46a7-9f50-578091d4e58c/could-not-load-file-or-assembly-presentationframework?forum=wpf)

[Dashboard_ErrorReport_472017_103025.txt](https://github.com/navhaxs/minecraft-server-dashboard/files/1121422/Dashboard_ErrorReport_472017_103025.txt)

**Comment by navhaxs** [comment]
Which Windows 10 theme are you using? Is it a custom theme?

Can you try https://github.com/navhaxs/minecraft-server-dashboard/releases/download/test%2FWPFcustomMsstyles/Dashboard-test-msstyles.zip ?

You can also try changing back to the default Windows 10 aero theme, and see if it still crashes.

-Jeremy

**Comment by ErikSteiner** [comment]
LOL. Yes you were right. The theme was set to custom, but I was never bothered by the naming. I set it to default, changed the background images and colors to my liking and successfully run the dashboard..
Thank you!

**Comment by navhaxs** [comment]
👍
