### ISSUE TITLE
Error Startup --nojline support removed (Java 8 201 x64 or fabric-launcher?)

### ISSUE THREAD

**Issue by VegethB** [navhaxs/minecraft-server-dashboard#9]
As the title suggests, when you start a modded server (fabric from minecraft vanilla 1.14) with the --nojline command, the server is closed.

**Comment by Sparks01** [comment]
I don't know if this is still being monitored but I also can confirm this problem. Though, I'm not sure that my server is modded.

**Comment by navhaxs** [comment]
@zFerry98 @Sparks01 
Hey guys, thanks for reporting the problem.

Can you please try https://github.com/navhaxs/minecraft-server-dashboard/releases/tag/v1.0.1

I have just added a new option `Use --nojline parameter (Default: Enabled)` in `Java, Memory & Startup`. Just uncheck this option, and see if that helps :)

Also pls note that this is a REALLY old project of mine from 2013 (!) so I can't provide too much support...and most of the code is pretty bad... but its cool that people are still using it today

**Comment by navhaxs** [comment]
Please do report back if it works (or not) so I can mark this issue as resolved. Thanks!

**Comment by Sparks01** [comment]
Works for me. Thanks so much. 

I know this is old software, but I want you to know that I find it the best for simple managing of a home server. I run one for my kid and this is for me the best front end for dealing with this. It's straight up, very user friendly and doesn't require a lot of complicated set up.  Maybe someone will pick up the torch in the future. Thanks so much for making this fix. Much appreciated. 

Cheers!

**Comment by VegethB** [comment]
Resolved!
As Sparks01 said, this software allows you to manage any server (fabric, forge, paper / spigot, vanilla etc.) the only one that can compete is bukkit gui v1.8 (v2 does not support generic .jar) and so this makes your application the best alternative for servers.
Thanks to the availability
